# Generated by Django 5.2.17 on 2026-09-28 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='ID во внешней системе')),
                ('email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Текст письма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено')], default='pending', max_length=16, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Письмо рассылки',
                'verbose_name_plural': 'Письма рассылки',
                'ordering': ('-created_at',),
            },
        ),
    ]
